task: panellinies_exams_computer_science_open
dataset_path: PennyK98/panellinies_exams_dataset
output_type: generate_until
test_split: train
process_docs: !function utils.process_computer_science_open
doc_to_text: !function utils.doc_to_text_open
doc_to_target: !function utils.doc_to_target_open
generation_kwargs:
  do_sample: false
  temperature: 0.0
  max_gen_toks: 512
  until: ["Ερώτηση:", "---"]
metric_list:
  - metric: chrf
    aggregation: mean
    higher_is_better: true