# yaml-language-server: $schema=none
group: panellinies_closed_aggregate
task:
  - panellinies_ancient_greek_closed
  - panellinies_economics_closed
  - panellinies_physics_closed
  - panellinies_history_closed
  - panellinies_latin_closed
  - panellinies_mathematics_closed
  - panellinies_greek_language_closed
  - panellinies_computer_science_closed
  - panellinies_chemistry_closed
  - panellinies_biology_closed
aggregate_metric_list:
  - metric: exact_match
    aggregation: mean