group: panellinies_open_aggregate
task:
  - panellinies_ancient_greek_open
  - panellinies_economics_open
  - panellinies_physics_open
  - panellinies_history_open
  - panellinies_latin_open
  - panellinies_mathematics_open
  - panellinies_greek_language_open
  - panellinies_computer_science_open
  - panellinies_chemistry_open
  - panellinies_biology_open
aggregate_metric_list:
  - metric: bertscore_f1_max
    aggregation: mean