group: panellinies_structured_aggregate_private
task:
  - panellinies_ancient_greek_structured_private
  - panellinies_latin_structured_private
  - panellinies_computer_science_structured_private
  - panellinies_biology_structured_private
aggregate_metric_list:
  - metric: structured_accuracy
    aggregation: mean